blank_issues_enabled: false
contact_links:
  - name: Open Business Policy discussions
    url: https://github.com/JEleniel/open-business-policy/discussions
    about: Please ask and answer questions here.
