title: The Open Business Policy
description: A set of ethical, evidence-based busines policies and procedures
jekyllurl: "https://jeleniel.github.io/open-business-policy/"
github_username:  JEleniel

theme: slate
plugins:
  - jekyll-feed
  - jemoji
